import type { LucideIcon } from "lucide-react"
import {
  Wifi,
  Waves,
  Sun,
  Umbrella,
  TreePalm,
  Car,
  SquareParking,
  Utensils,
  Coffee,
  Bath,
  Bed,
  BedDouble,
  Tv,
  Snowflake,
  Flame,
  Fan,
  WashingMachine,
  PawPrint,
  Baby,
  Dumbbell,
  Bike,
  MapPin,
  Key,
  ShieldCheck,
  Sparkles,
  Star,
  Heart,
  Clock,
  Calendar,
  Phone,
  Mail,
  Users,
  House,
  Check,
  CircleCheck,
  ThumbsUp,
  BadgeCheck,
  Award,
  Handshake,
  Headphones,
  MessageCircle,
  CreditCard,
  Wallet,
  Tag,
  Percent,
  Leaf,
  Mountain,
  Tent,
  Fish,
  Sailboat,
  Anchor,
  Plane,
  Bus,
  Luggage,
  ShoppingCart,
  Store,
  Wine,
  Beer,
  CookingPot,
  Refrigerator,
  Microwave,
  Flower,
  Trees,
  Sunrise,
  Sunset,
  Moon,
  CloudSun,
  Wind,
  Droplets,
  Thermometer,
  Lock,
  Eye,
  Globe,
  Compass,
  Lightbulb,
  Zap,
  Wrench,
  ShowerHead,
  Sofa,
  Shirt,
  Gift,
  Camera,
  Binoculars,
  Footprints,
  Volleyball,
  Building2,
  Smile,
  Accessibility,
  CigaretteOff,
} from "lucide-react"

import { isIconName, type IconName } from "./icons"

/**
 * The component for each name on the list (`icons.ts`). Only these icons
 * are imported, by name, so the rest of Lucide stays out of the bundle. The
 * compiler asks for a component whenever a name is added to the list.
 */
export const iconComponents: Record<IconName, LucideIcon> = {
  wifi: Wifi,
  waves: Waves,
  sun: Sun,
  umbrella: Umbrella,
  "tree-palm": TreePalm,
  car: Car,
  "square-parking": SquareParking,
  utensils: Utensils,
  coffee: Coffee,
  bath: Bath,
  bed: Bed,
  "bed-double": BedDouble,
  tv: Tv,
  snowflake: Snowflake,
  flame: Flame,
  fan: Fan,
  "washing-machine": WashingMachine,
  "paw-print": PawPrint,
  baby: Baby,
  dumbbell: Dumbbell,
  bike: Bike,
  "map-pin": MapPin,
  key: Key,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  clock: Clock,
  calendar: Calendar,
  phone: Phone,
  mail: Mail,
  users: Users,
  house: House,
  check: Check,
  "circle-check": CircleCheck,
  "thumbs-up": ThumbsUp,
  "badge-check": BadgeCheck,
  award: Award,
  handshake: Handshake,
  headphones: Headphones,
  "message-circle": MessageCircle,
  "credit-card": CreditCard,
  wallet: Wallet,
  tag: Tag,
  percent: Percent,
  leaf: Leaf,
  mountain: Mountain,
  tent: Tent,
  fish: Fish,
  sailboat: Sailboat,
  anchor: Anchor,
  plane: Plane,
  bus: Bus,
  luggage: Luggage,
  "shopping-cart": ShoppingCart,
  store: Store,
  wine: Wine,
  beer: Beer,
  "cooking-pot": CookingPot,
  refrigerator: Refrigerator,
  microwave: Microwave,
  flower: Flower,
  trees: Trees,
  sunrise: Sunrise,
  sunset: Sunset,
  moon: Moon,
  "cloud-sun": CloudSun,
  wind: Wind,
  droplets: Droplets,
  thermometer: Thermometer,
  lock: Lock,
  eye: Eye,
  globe: Globe,
  compass: Compass,
  lightbulb: Lightbulb,
  zap: Zap,
  wrench: Wrench,
  "shower-head": ShowerHead,
  sofa: Sofa,
  shirt: Shirt,
  gift: Gift,
  camera: Camera,
  binoculars: Binoculars,
  footprints: Footprints,
  volleyball: Volleyball,
  "building-2": Building2,
  smile: Smile,
  accessibility: Accessibility,
  "cigarette-off": CigaretteOff,
}

/**
 * A Lucide icon by name, decorative (hidden from assistive technology: the
 * text beside it says what it means). Renders nothing for a name that is
 * not on the list, such as one that was removed after a Page saved it.
 */
export function Icon({
  name,
  className,
}: {
  name: string | null | undefined
  className?: string
}) {
  if (!isIconName(name)) return null
  const Component = iconComponents[name]
  return <Component aria-hidden="true" className={className} />
}
