import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-postgres"

import { setSiteSchema } from "../setSiteSchema"

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await setSiteSchema(db, payload)
  await db.execute(sql`
   CREATE TYPE "enum_pages_blocks_rich_text_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_call_to_action_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_featured_rentals_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_large_group_rentals_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_rental_grid_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_steps_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_features_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_amenities_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_stats_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_image_text_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_testimonials_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_trust_strip_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_owner_band_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_newsletter_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_blog_teaser_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_location_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_faq_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_form_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_guest_survey_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_container_3_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_container_2_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_pages_blocks_container_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_rich_text_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_call_to_action_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_featured_rentals_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_large_group_rentals_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_rental_grid_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_steps_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_features_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_amenities_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_stats_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_image_text_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_testimonials_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_trust_strip_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_owner_band_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_newsletter_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_blog_teaser_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_location_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_faq_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_form_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_guest_survey_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_container_3_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_container_2_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__pages_v_blocks_container_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_utility_strip_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum_layouts_blocks_utility_strip_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_footer_columns_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum_layouts_blocks_footer_columns_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_legal_bar_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum_layouts_blocks_legal_bar_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_newsletter_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_call_to_action_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_container_3_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_container_2_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum_layouts_blocks_container_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_utility_strip_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_utility_strip_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_footer_columns_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_footer_columns_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_legal_bar_background" AS ENUM('default', 'muted', 'primary', 'accent', 'third', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_legal_bar_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_newsletter_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_call_to_action_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_container_3_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_container_2_text_colour" AS ENUM('auto', 'white', 'dark');
  CREATE TYPE "enum__layouts_v_blocks_container_text_colour" AS ENUM('auto', 'white', 'dark');
  ALTER TYPE "enum_pages_blocks_rich_text_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_rich_text_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_call_to_action_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_call_to_action_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_featured_rentals_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_featured_rentals_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_large_group_rentals_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_large_group_rentals_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_rental_grid_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_rental_grid_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_steps_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_steps_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_features_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_features_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_amenities_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_amenities_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_stats_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_stats_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_image_text_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_image_text_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_testimonials_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_testimonials_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_trust_strip_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_trust_strip_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_owner_band_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_owner_band_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_newsletter_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_newsletter_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_blog_teaser_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_blog_teaser_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_location_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_location_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_faq_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_faq_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_form_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_form_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_guest_survey_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_guest_survey_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_3_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_3_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_2_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_2_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_pages_blocks_container_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_rich_text_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_rich_text_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_call_to_action_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_call_to_action_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_featured_rentals_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_featured_rentals_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_large_group_rentals_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_large_group_rentals_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_rental_grid_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_rental_grid_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_steps_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_steps_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_features_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_features_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_amenities_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_amenities_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_stats_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_stats_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_image_text_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_image_text_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_testimonials_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_testimonials_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_trust_strip_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_trust_strip_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_owner_band_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_owner_band_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_newsletter_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_newsletter_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_blog_teaser_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_blog_teaser_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_location_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_location_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_faq_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_faq_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_form_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_form_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_guest_survey_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_guest_survey_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_3_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_3_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_2_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_2_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__pages_v_blocks_container_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_newsletter_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_newsletter_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_call_to_action_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_call_to_action_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_3_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_3_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_2_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_2_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum_layouts_blocks_container_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_newsletter_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_newsletter_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_call_to_action_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_call_to_action_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_3_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_3_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_2_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_2_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_background" ADD VALUE 'accent' BEFORE 'dark';
  ALTER TYPE "enum__layouts_v_blocks_container_background" ADD VALUE 'third' BEFORE 'dark';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "text_colour" "enum_pages_blocks_rich_text_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_call_to_action" ADD COLUMN "text_colour" "enum_pages_blocks_call_to_action_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_featured_rentals" ADD COLUMN "text_colour" "enum_pages_blocks_featured_rentals_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_large_group_rentals" ADD COLUMN "text_colour" "enum_pages_blocks_large_group_rentals_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_rental_grid" ADD COLUMN "text_colour" "enum_pages_blocks_rental_grid_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "text_colour" "enum_pages_blocks_steps_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_features" ADD COLUMN "text_colour" "enum_pages_blocks_features_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_amenities" ADD COLUMN "text_colour" "enum_pages_blocks_amenities_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "text_colour" "enum_pages_blocks_stats_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_image_text" ADD COLUMN "text_colour" "enum_pages_blocks_image_text_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "text_colour" "enum_pages_blocks_testimonials_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_trust_strip" ADD COLUMN "text_colour" "enum_pages_blocks_trust_strip_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_owner_band" ADD COLUMN "text_colour" "enum_pages_blocks_owner_band_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "text_colour" "enum_pages_blocks_newsletter_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_blog_teaser" ADD COLUMN "text_colour" "enum_pages_blocks_blog_teaser_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_location" ADD COLUMN "text_colour" "enum_pages_blocks_location_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "text_colour" "enum_pages_blocks_faq_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_form" ADD COLUMN "text_colour" "enum_pages_blocks_form_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_guest_survey" ADD COLUMN "text_colour" "enum_pages_blocks_guest_survey_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_container_3" ADD COLUMN "text_colour" "enum_pages_blocks_container_3_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_container_2" ADD COLUMN "text_colour" "enum_pages_blocks_container_2_text_colour" DEFAULT 'auto';
  ALTER TABLE "pages_blocks_container" ADD COLUMN "text_colour" "enum_pages_blocks_container_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "text_colour" "enum__pages_v_blocks_rich_text_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_call_to_action" ADD COLUMN "text_colour" "enum__pages_v_blocks_call_to_action_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_featured_rentals" ADD COLUMN "text_colour" "enum__pages_v_blocks_featured_rentals_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_large_group_rentals" ADD COLUMN "text_colour" "enum__pages_v_blocks_large_group_rentals_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_rental_grid" ADD COLUMN "text_colour" "enum__pages_v_blocks_rental_grid_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "text_colour" "enum__pages_v_blocks_steps_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_features" ADD COLUMN "text_colour" "enum__pages_v_blocks_features_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_amenities" ADD COLUMN "text_colour" "enum__pages_v_blocks_amenities_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "text_colour" "enum__pages_v_blocks_stats_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_image_text" ADD COLUMN "text_colour" "enum__pages_v_blocks_image_text_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "text_colour" "enum__pages_v_blocks_testimonials_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_trust_strip" ADD COLUMN "text_colour" "enum__pages_v_blocks_trust_strip_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_owner_band" ADD COLUMN "text_colour" "enum__pages_v_blocks_owner_band_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "text_colour" "enum__pages_v_blocks_newsletter_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_blog_teaser" ADD COLUMN "text_colour" "enum__pages_v_blocks_blog_teaser_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_location" ADD COLUMN "text_colour" "enum__pages_v_blocks_location_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "text_colour" "enum__pages_v_blocks_faq_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_form" ADD COLUMN "text_colour" "enum__pages_v_blocks_form_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_guest_survey" ADD COLUMN "text_colour" "enum__pages_v_blocks_guest_survey_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_container_3" ADD COLUMN "text_colour" "enum__pages_v_blocks_container_3_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_container_2" ADD COLUMN "text_colour" "enum__pages_v_blocks_container_2_text_colour" DEFAULT 'auto';
  ALTER TABLE "_pages_v_blocks_container" ADD COLUMN "text_colour" "enum__pages_v_blocks_container_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_utility_strip" ADD COLUMN "background" "enum_layouts_blocks_utility_strip_background" DEFAULT 'default';
  ALTER TABLE "layouts_blocks_utility_strip" ADD COLUMN "text_colour" "enum_layouts_blocks_utility_strip_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_footer_columns" ADD COLUMN "background" "enum_layouts_blocks_footer_columns_background" DEFAULT 'default';
  ALTER TABLE "layouts_blocks_footer_columns" ADD COLUMN "text_colour" "enum_layouts_blocks_footer_columns_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_legal_bar" ADD COLUMN "background" "enum_layouts_blocks_legal_bar_background" DEFAULT 'default';
  ALTER TABLE "layouts_blocks_legal_bar" ADD COLUMN "text_colour" "enum_layouts_blocks_legal_bar_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_newsletter" ADD COLUMN "text_colour" "enum_layouts_blocks_newsletter_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_call_to_action" ADD COLUMN "text_colour" "enum_layouts_blocks_call_to_action_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_container_3" ADD COLUMN "text_colour" "enum_layouts_blocks_container_3_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_container_2" ADD COLUMN "text_colour" "enum_layouts_blocks_container_2_text_colour" DEFAULT 'auto';
  ALTER TABLE "layouts_blocks_container" ADD COLUMN "text_colour" "enum_layouts_blocks_container_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_utility_strip" ADD COLUMN "background" "enum__layouts_v_blocks_utility_strip_background" DEFAULT 'default';
  ALTER TABLE "_layouts_v_blocks_utility_strip" ADD COLUMN "text_colour" "enum__layouts_v_blocks_utility_strip_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_footer_columns" ADD COLUMN "background" "enum__layouts_v_blocks_footer_columns_background" DEFAULT 'default';
  ALTER TABLE "_layouts_v_blocks_footer_columns" ADD COLUMN "text_colour" "enum__layouts_v_blocks_footer_columns_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_legal_bar" ADD COLUMN "background" "enum__layouts_v_blocks_legal_bar_background" DEFAULT 'default';
  ALTER TABLE "_layouts_v_blocks_legal_bar" ADD COLUMN "text_colour" "enum__layouts_v_blocks_legal_bar_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_newsletter" ADD COLUMN "text_colour" "enum__layouts_v_blocks_newsletter_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_call_to_action" ADD COLUMN "text_colour" "enum__layouts_v_blocks_call_to_action_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_container_3" ADD COLUMN "text_colour" "enum__layouts_v_blocks_container_3_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_container_2" ADD COLUMN "text_colour" "enum__layouts_v_blocks_container_2_text_colour" DEFAULT 'auto';
  ALTER TABLE "_layouts_v_blocks_container" ADD COLUMN "text_colour" "enum__layouts_v_blocks_container_text_colour" DEFAULT 'auto';`)
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  await setSiteSchema(db, payload)
  await db.execute(sql`
   ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_rich_text_background";
  CREATE TYPE "enum_pages_blocks_rich_text_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_rich_text_background";
  ALTER TABLE "pages_blocks_rich_text" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_rich_text_background" USING "background"::"enum_pages_blocks_rich_text_background";
  ALTER TABLE "pages_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_call_to_action_background";
  CREATE TYPE "enum_pages_blocks_call_to_action_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_call_to_action_background";
  ALTER TABLE "pages_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_call_to_action_background" USING "background"::"enum_pages_blocks_call_to_action_background";
  ALTER TABLE "pages_blocks_featured_rentals" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_featured_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_featured_rentals_background";
  CREATE TYPE "enum_pages_blocks_featured_rentals_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_featured_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_featured_rentals_background";
  ALTER TABLE "pages_blocks_featured_rentals" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_featured_rentals_background" USING "background"::"enum_pages_blocks_featured_rentals_background";
  ALTER TABLE "pages_blocks_large_group_rentals" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_large_group_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_large_group_rentals_background";
  CREATE TYPE "enum_pages_blocks_large_group_rentals_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_large_group_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_large_group_rentals_background";
  ALTER TABLE "pages_blocks_large_group_rentals" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_large_group_rentals_background" USING "background"::"enum_pages_blocks_large_group_rentals_background";
  ALTER TABLE "pages_blocks_rental_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_rental_grid" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_rental_grid_background";
  CREATE TYPE "enum_pages_blocks_rental_grid_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_rental_grid" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_rental_grid_background";
  ALTER TABLE "pages_blocks_rental_grid" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_rental_grid_background" USING "background"::"enum_pages_blocks_rental_grid_background";
  ALTER TABLE "pages_blocks_steps" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_steps" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_steps_background";
  CREATE TYPE "enum_pages_blocks_steps_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_steps" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_steps_background";
  ALTER TABLE "pages_blocks_steps" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_steps_background" USING "background"::"enum_pages_blocks_steps_background";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_features_background";
  CREATE TYPE "enum_pages_blocks_features_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_features_background";
  ALTER TABLE "pages_blocks_features" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_features_background" USING "background"::"enum_pages_blocks_features_background";
  ALTER TABLE "pages_blocks_amenities" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_amenities" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_amenities_background";
  CREATE TYPE "enum_pages_blocks_amenities_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_amenities" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_amenities_background";
  ALTER TABLE "pages_blocks_amenities" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_amenities_background" USING "background"::"enum_pages_blocks_amenities_background";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_stats_background";
  CREATE TYPE "enum_pages_blocks_stats_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_stats_background";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_stats_background" USING "background"::"enum_pages_blocks_stats_background";
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_image_text_background";
  CREATE TYPE "enum_pages_blocks_image_text_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_image_text_background";
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_image_text_background" USING "background"::"enum_pages_blocks_image_text_background";
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_testimonials_background";
  CREATE TYPE "enum_pages_blocks_testimonials_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_testimonials_background";
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_testimonials_background" USING "background"::"enum_pages_blocks_testimonials_background";
  ALTER TABLE "pages_blocks_trust_strip" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_trust_strip" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_trust_strip_background";
  CREATE TYPE "enum_pages_blocks_trust_strip_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_trust_strip" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_trust_strip_background";
  ALTER TABLE "pages_blocks_trust_strip" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_trust_strip_background" USING "background"::"enum_pages_blocks_trust_strip_background";
  ALTER TABLE "pages_blocks_owner_band" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_owner_band" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "enum_pages_blocks_owner_band_background";
  CREATE TYPE "enum_pages_blocks_owner_band_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_owner_band" ALTER COLUMN "background" SET DEFAULT 'dark'::"enum_pages_blocks_owner_band_background";
  ALTER TABLE "pages_blocks_owner_band" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_owner_band_background" USING "background"::"enum_pages_blocks_owner_band_background";
  ALTER TABLE "pages_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_newsletter_background";
  CREATE TYPE "enum_pages_blocks_newsletter_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_newsletter_background";
  ALTER TABLE "pages_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_newsletter_background" USING "background"::"enum_pages_blocks_newsletter_background";
  ALTER TABLE "pages_blocks_blog_teaser" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_blog_teaser" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_blog_teaser_background";
  CREATE TYPE "enum_pages_blocks_blog_teaser_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_blog_teaser" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_blog_teaser_background";
  ALTER TABLE "pages_blocks_blog_teaser" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_blog_teaser_background" USING "background"::"enum_pages_blocks_blog_teaser_background";
  ALTER TABLE "pages_blocks_location" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_location" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_location_background";
  CREATE TYPE "enum_pages_blocks_location_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_location" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_location_background";
  ALTER TABLE "pages_blocks_location" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_location_background" USING "background"::"enum_pages_blocks_location_background";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_faq_background";
  CREATE TYPE "enum_pages_blocks_faq_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_faq_background";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_faq_background" USING "background"::"enum_pages_blocks_faq_background";
  ALTER TABLE "pages_blocks_form" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_form" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_form_background";
  CREATE TYPE "enum_pages_blocks_form_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_form" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_form_background";
  ALTER TABLE "pages_blocks_form" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_form_background" USING "background"::"enum_pages_blocks_form_background";
  ALTER TABLE "pages_blocks_guest_survey" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_guest_survey" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_guest_survey_background";
  CREATE TYPE "enum_pages_blocks_guest_survey_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_guest_survey" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_guest_survey_background";
  ALTER TABLE "pages_blocks_guest_survey" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_guest_survey_background" USING "background"::"enum_pages_blocks_guest_survey_background";
  ALTER TABLE "pages_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_container_3_background";
  CREATE TYPE "enum_pages_blocks_container_3_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_container_3_background";
  ALTER TABLE "pages_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_container_3_background" USING "background"::"enum_pages_blocks_container_3_background";
  ALTER TABLE "pages_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_container_2_background";
  CREATE TYPE "enum_pages_blocks_container_2_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_container_2_background";
  ALTER TABLE "pages_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_container_2_background" USING "background"::"enum_pages_blocks_container_2_background";
  ALTER TABLE "pages_blocks_container" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_pages_blocks_container_background";
  CREATE TYPE "enum_pages_blocks_container_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "pages_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_pages_blocks_container_background";
  ALTER TABLE "pages_blocks_container" ALTER COLUMN "background" SET DATA TYPE "enum_pages_blocks_container_background" USING "background"::"enum_pages_blocks_container_background";
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_rich_text_background";
  CREATE TYPE "enum__pages_v_blocks_rich_text_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_rich_text_background";
  ALTER TABLE "_pages_v_blocks_rich_text" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_rich_text_background" USING "background"::"enum__pages_v_blocks_rich_text_background";
  ALTER TABLE "_pages_v_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_call_to_action_background";
  CREATE TYPE "enum__pages_v_blocks_call_to_action_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_call_to_action_background";
  ALTER TABLE "_pages_v_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_call_to_action_background" USING "background"::"enum__pages_v_blocks_call_to_action_background";
  ALTER TABLE "_pages_v_blocks_featured_rentals" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_featured_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_featured_rentals_background";
  CREATE TYPE "enum__pages_v_blocks_featured_rentals_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_featured_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_featured_rentals_background";
  ALTER TABLE "_pages_v_blocks_featured_rentals" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_featured_rentals_background" USING "background"::"enum__pages_v_blocks_featured_rentals_background";
  ALTER TABLE "_pages_v_blocks_large_group_rentals" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_large_group_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_large_group_rentals_background";
  CREATE TYPE "enum__pages_v_blocks_large_group_rentals_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_large_group_rentals" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_large_group_rentals_background";
  ALTER TABLE "_pages_v_blocks_large_group_rentals" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_large_group_rentals_background" USING "background"::"enum__pages_v_blocks_large_group_rentals_background";
  ALTER TABLE "_pages_v_blocks_rental_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_rental_grid" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_rental_grid_background";
  CREATE TYPE "enum__pages_v_blocks_rental_grid_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_rental_grid" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_rental_grid_background";
  ALTER TABLE "_pages_v_blocks_rental_grid" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_rental_grid_background" USING "background"::"enum__pages_v_blocks_rental_grid_background";
  ALTER TABLE "_pages_v_blocks_steps" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_steps" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_steps_background";
  CREATE TYPE "enum__pages_v_blocks_steps_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_steps" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_steps_background";
  ALTER TABLE "_pages_v_blocks_steps" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_steps_background" USING "background"::"enum__pages_v_blocks_steps_background";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_features_background";
  CREATE TYPE "enum__pages_v_blocks_features_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_features_background";
  ALTER TABLE "_pages_v_blocks_features" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_features_background" USING "background"::"enum__pages_v_blocks_features_background";
  ALTER TABLE "_pages_v_blocks_amenities" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_amenities" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_amenities_background";
  CREATE TYPE "enum__pages_v_blocks_amenities_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_amenities" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_amenities_background";
  ALTER TABLE "_pages_v_blocks_amenities" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_amenities_background" USING "background"::"enum__pages_v_blocks_amenities_background";
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_stats_background";
  CREATE TYPE "enum__pages_v_blocks_stats_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_stats_background";
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_stats_background" USING "background"::"enum__pages_v_blocks_stats_background";
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_image_text_background";
  CREATE TYPE "enum__pages_v_blocks_image_text_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_image_text_background";
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_image_text_background" USING "background"::"enum__pages_v_blocks_image_text_background";
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_testimonials_background";
  CREATE TYPE "enum__pages_v_blocks_testimonials_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_testimonials_background";
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_testimonials_background" USING "background"::"enum__pages_v_blocks_testimonials_background";
  ALTER TABLE "_pages_v_blocks_trust_strip" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_trust_strip" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_trust_strip_background";
  CREATE TYPE "enum__pages_v_blocks_trust_strip_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_trust_strip" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_trust_strip_background";
  ALTER TABLE "_pages_v_blocks_trust_strip" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_trust_strip_background" USING "background"::"enum__pages_v_blocks_trust_strip_background";
  ALTER TABLE "_pages_v_blocks_owner_band" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_owner_band" ALTER COLUMN "background" SET DEFAULT 'dark'::text;
  DROP TYPE "enum__pages_v_blocks_owner_band_background";
  CREATE TYPE "enum__pages_v_blocks_owner_band_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_owner_band" ALTER COLUMN "background" SET DEFAULT 'dark'::"enum__pages_v_blocks_owner_band_background";
  ALTER TABLE "_pages_v_blocks_owner_band" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_owner_band_background" USING "background"::"enum__pages_v_blocks_owner_band_background";
  ALTER TABLE "_pages_v_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_newsletter_background";
  CREATE TYPE "enum__pages_v_blocks_newsletter_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_newsletter_background";
  ALTER TABLE "_pages_v_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_newsletter_background" USING "background"::"enum__pages_v_blocks_newsletter_background";
  ALTER TABLE "_pages_v_blocks_blog_teaser" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_blog_teaser" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_blog_teaser_background";
  CREATE TYPE "enum__pages_v_blocks_blog_teaser_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_blog_teaser" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_blog_teaser_background";
  ALTER TABLE "_pages_v_blocks_blog_teaser" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_blog_teaser_background" USING "background"::"enum__pages_v_blocks_blog_teaser_background";
  ALTER TABLE "_pages_v_blocks_location" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_location" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_location_background";
  CREATE TYPE "enum__pages_v_blocks_location_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_location" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_location_background";
  ALTER TABLE "_pages_v_blocks_location" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_location_background" USING "background"::"enum__pages_v_blocks_location_background";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_faq_background";
  CREATE TYPE "enum__pages_v_blocks_faq_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_faq_background";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_faq_background" USING "background"::"enum__pages_v_blocks_faq_background";
  ALTER TABLE "_pages_v_blocks_form" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_form" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_form_background";
  CREATE TYPE "enum__pages_v_blocks_form_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_form" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_form_background";
  ALTER TABLE "_pages_v_blocks_form" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_form_background" USING "background"::"enum__pages_v_blocks_form_background";
  ALTER TABLE "_pages_v_blocks_guest_survey" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_guest_survey" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_guest_survey_background";
  CREATE TYPE "enum__pages_v_blocks_guest_survey_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_guest_survey" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_guest_survey_background";
  ALTER TABLE "_pages_v_blocks_guest_survey" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_guest_survey_background" USING "background"::"enum__pages_v_blocks_guest_survey_background";
  ALTER TABLE "_pages_v_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_container_3_background";
  CREATE TYPE "enum__pages_v_blocks_container_3_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_container_3_background";
  ALTER TABLE "_pages_v_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_container_3_background" USING "background"::"enum__pages_v_blocks_container_3_background";
  ALTER TABLE "_pages_v_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_container_2_background";
  CREATE TYPE "enum__pages_v_blocks_container_2_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_container_2_background";
  ALTER TABLE "_pages_v_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_container_2_background" USING "background"::"enum__pages_v_blocks_container_2_background";
  ALTER TABLE "_pages_v_blocks_container" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__pages_v_blocks_container_background";
  CREATE TYPE "enum__pages_v_blocks_container_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_pages_v_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__pages_v_blocks_container_background";
  ALTER TABLE "_pages_v_blocks_container" ALTER COLUMN "background" SET DATA TYPE "enum__pages_v_blocks_container_background" USING "background"::"enum__pages_v_blocks_container_background";
  ALTER TABLE "layouts_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "layouts_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_layouts_blocks_newsletter_background";
  CREATE TYPE "enum_layouts_blocks_newsletter_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "layouts_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_layouts_blocks_newsletter_background";
  ALTER TABLE "layouts_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE "enum_layouts_blocks_newsletter_background" USING "background"::"enum_layouts_blocks_newsletter_background";
  ALTER TABLE "layouts_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "layouts_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_layouts_blocks_call_to_action_background";
  CREATE TYPE "enum_layouts_blocks_call_to_action_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "layouts_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_layouts_blocks_call_to_action_background";
  ALTER TABLE "layouts_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE "enum_layouts_blocks_call_to_action_background" USING "background"::"enum_layouts_blocks_call_to_action_background";
  ALTER TABLE "layouts_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "layouts_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_layouts_blocks_container_3_background";
  CREATE TYPE "enum_layouts_blocks_container_3_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "layouts_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_layouts_blocks_container_3_background";
  ALTER TABLE "layouts_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE "enum_layouts_blocks_container_3_background" USING "background"::"enum_layouts_blocks_container_3_background";
  ALTER TABLE "layouts_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "layouts_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_layouts_blocks_container_2_background";
  CREATE TYPE "enum_layouts_blocks_container_2_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "layouts_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_layouts_blocks_container_2_background";
  ALTER TABLE "layouts_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE "enum_layouts_blocks_container_2_background" USING "background"::"enum_layouts_blocks_container_2_background";
  ALTER TABLE "layouts_blocks_container" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "layouts_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum_layouts_blocks_container_background";
  CREATE TYPE "enum_layouts_blocks_container_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "layouts_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::"enum_layouts_blocks_container_background";
  ALTER TABLE "layouts_blocks_container" ALTER COLUMN "background" SET DATA TYPE "enum_layouts_blocks_container_background" USING "background"::"enum_layouts_blocks_container_background";
  ALTER TABLE "_layouts_v_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_layouts_v_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__layouts_v_blocks_newsletter_background";
  CREATE TYPE "enum__layouts_v_blocks_newsletter_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_layouts_v_blocks_newsletter" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__layouts_v_blocks_newsletter_background";
  ALTER TABLE "_layouts_v_blocks_newsletter" ALTER COLUMN "background" SET DATA TYPE "enum__layouts_v_blocks_newsletter_background" USING "background"::"enum__layouts_v_blocks_newsletter_background";
  ALTER TABLE "_layouts_v_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_layouts_v_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__layouts_v_blocks_call_to_action_background";
  CREATE TYPE "enum__layouts_v_blocks_call_to_action_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_layouts_v_blocks_call_to_action" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__layouts_v_blocks_call_to_action_background";
  ALTER TABLE "_layouts_v_blocks_call_to_action" ALTER COLUMN "background" SET DATA TYPE "enum__layouts_v_blocks_call_to_action_background" USING "background"::"enum__layouts_v_blocks_call_to_action_background";
  ALTER TABLE "_layouts_v_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_layouts_v_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__layouts_v_blocks_container_3_background";
  CREATE TYPE "enum__layouts_v_blocks_container_3_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_layouts_v_blocks_container_3" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__layouts_v_blocks_container_3_background";
  ALTER TABLE "_layouts_v_blocks_container_3" ALTER COLUMN "background" SET DATA TYPE "enum__layouts_v_blocks_container_3_background" USING "background"::"enum__layouts_v_blocks_container_3_background";
  ALTER TABLE "_layouts_v_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_layouts_v_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__layouts_v_blocks_container_2_background";
  CREATE TYPE "enum__layouts_v_blocks_container_2_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_layouts_v_blocks_container_2" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__layouts_v_blocks_container_2_background";
  ALTER TABLE "_layouts_v_blocks_container_2" ALTER COLUMN "background" SET DATA TYPE "enum__layouts_v_blocks_container_2_background" USING "background"::"enum__layouts_v_blocks_container_2_background";
  ALTER TABLE "_layouts_v_blocks_container" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_layouts_v_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::text;
  DROP TYPE "enum__layouts_v_blocks_container_background";
  CREATE TYPE "enum__layouts_v_blocks_container_background" AS ENUM('default', 'muted', 'primary', 'dark');
  ALTER TABLE "_layouts_v_blocks_container" ALTER COLUMN "background" SET DEFAULT 'default'::"enum__layouts_v_blocks_container_background";
  ALTER TABLE "_layouts_v_blocks_container" ALTER COLUMN "background" SET DATA TYPE "enum__layouts_v_blocks_container_background" USING "background"::"enum__layouts_v_blocks_container_background";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_call_to_action" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_featured_rentals" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_large_group_rentals" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_rental_grid" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_features" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_amenities" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_image_text" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_trust_strip" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_owner_band" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_blog_teaser" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_location" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_form" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_guest_survey" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_container_3" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_container_2" DROP COLUMN "text_colour";
  ALTER TABLE "pages_blocks_container" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_call_to_action" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_featured_rentals" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_large_group_rentals" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_rental_grid" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_features" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_amenities" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_image_text" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_trust_strip" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_owner_band" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_blog_teaser" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_location" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_form" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_guest_survey" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_container_3" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_container_2" DROP COLUMN "text_colour";
  ALTER TABLE "_pages_v_blocks_container" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_utility_strip" DROP COLUMN "background";
  ALTER TABLE "layouts_blocks_utility_strip" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_footer_columns" DROP COLUMN "background";
  ALTER TABLE "layouts_blocks_footer_columns" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_legal_bar" DROP COLUMN "background";
  ALTER TABLE "layouts_blocks_legal_bar" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_newsletter" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_call_to_action" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_container_3" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_container_2" DROP COLUMN "text_colour";
  ALTER TABLE "layouts_blocks_container" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_utility_strip" DROP COLUMN "background";
  ALTER TABLE "_layouts_v_blocks_utility_strip" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_footer_columns" DROP COLUMN "background";
  ALTER TABLE "_layouts_v_blocks_footer_columns" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_legal_bar" DROP COLUMN "background";
  ALTER TABLE "_layouts_v_blocks_legal_bar" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_newsletter" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_call_to_action" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_container_3" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_container_2" DROP COLUMN "text_colour";
  ALTER TABLE "_layouts_v_blocks_container" DROP COLUMN "text_colour";
  DROP TYPE "enum_pages_blocks_rich_text_text_colour";
  DROP TYPE "enum_pages_blocks_call_to_action_text_colour";
  DROP TYPE "enum_pages_blocks_featured_rentals_text_colour";
  DROP TYPE "enum_pages_blocks_large_group_rentals_text_colour";
  DROP TYPE "enum_pages_blocks_rental_grid_text_colour";
  DROP TYPE "enum_pages_blocks_steps_text_colour";
  DROP TYPE "enum_pages_blocks_features_text_colour";
  DROP TYPE "enum_pages_blocks_amenities_text_colour";
  DROP TYPE "enum_pages_blocks_stats_text_colour";
  DROP TYPE "enum_pages_blocks_image_text_text_colour";
  DROP TYPE "enum_pages_blocks_testimonials_text_colour";
  DROP TYPE "enum_pages_blocks_trust_strip_text_colour";
  DROP TYPE "enum_pages_blocks_owner_band_text_colour";
  DROP TYPE "enum_pages_blocks_newsletter_text_colour";
  DROP TYPE "enum_pages_blocks_blog_teaser_text_colour";
  DROP TYPE "enum_pages_blocks_location_text_colour";
  DROP TYPE "enum_pages_blocks_faq_text_colour";
  DROP TYPE "enum_pages_blocks_form_text_colour";
  DROP TYPE "enum_pages_blocks_guest_survey_text_colour";
  DROP TYPE "enum_pages_blocks_container_3_text_colour";
  DROP TYPE "enum_pages_blocks_container_2_text_colour";
  DROP TYPE "enum_pages_blocks_container_text_colour";
  DROP TYPE "enum__pages_v_blocks_rich_text_text_colour";
  DROP TYPE "enum__pages_v_blocks_call_to_action_text_colour";
  DROP TYPE "enum__pages_v_blocks_featured_rentals_text_colour";
  DROP TYPE "enum__pages_v_blocks_large_group_rentals_text_colour";
  DROP TYPE "enum__pages_v_blocks_rental_grid_text_colour";
  DROP TYPE "enum__pages_v_blocks_steps_text_colour";
  DROP TYPE "enum__pages_v_blocks_features_text_colour";
  DROP TYPE "enum__pages_v_blocks_amenities_text_colour";
  DROP TYPE "enum__pages_v_blocks_stats_text_colour";
  DROP TYPE "enum__pages_v_blocks_image_text_text_colour";
  DROP TYPE "enum__pages_v_blocks_testimonials_text_colour";
  DROP TYPE "enum__pages_v_blocks_trust_strip_text_colour";
  DROP TYPE "enum__pages_v_blocks_owner_band_text_colour";
  DROP TYPE "enum__pages_v_blocks_newsletter_text_colour";
  DROP TYPE "enum__pages_v_blocks_blog_teaser_text_colour";
  DROP TYPE "enum__pages_v_blocks_location_text_colour";
  DROP TYPE "enum__pages_v_blocks_faq_text_colour";
  DROP TYPE "enum__pages_v_blocks_form_text_colour";
  DROP TYPE "enum__pages_v_blocks_guest_survey_text_colour";
  DROP TYPE "enum__pages_v_blocks_container_3_text_colour";
  DROP TYPE "enum__pages_v_blocks_container_2_text_colour";
  DROP TYPE "enum__pages_v_blocks_container_text_colour";
  DROP TYPE "enum_layouts_blocks_utility_strip_background";
  DROP TYPE "enum_layouts_blocks_utility_strip_text_colour";
  DROP TYPE "enum_layouts_blocks_footer_columns_background";
  DROP TYPE "enum_layouts_blocks_footer_columns_text_colour";
  DROP TYPE "enum_layouts_blocks_legal_bar_background";
  DROP TYPE "enum_layouts_blocks_legal_bar_text_colour";
  DROP TYPE "enum_layouts_blocks_newsletter_text_colour";
  DROP TYPE "enum_layouts_blocks_call_to_action_text_colour";
  DROP TYPE "enum_layouts_blocks_container_3_text_colour";
  DROP TYPE "enum_layouts_blocks_container_2_text_colour";
  DROP TYPE "enum_layouts_blocks_container_text_colour";
  DROP TYPE "enum__layouts_v_blocks_utility_strip_background";
  DROP TYPE "enum__layouts_v_blocks_utility_strip_text_colour";
  DROP TYPE "enum__layouts_v_blocks_footer_columns_background";
  DROP TYPE "enum__layouts_v_blocks_footer_columns_text_colour";
  DROP TYPE "enum__layouts_v_blocks_legal_bar_background";
  DROP TYPE "enum__layouts_v_blocks_legal_bar_text_colour";
  DROP TYPE "enum__layouts_v_blocks_newsletter_text_colour";
  DROP TYPE "enum__layouts_v_blocks_call_to_action_text_colour";
  DROP TYPE "enum__layouts_v_blocks_container_3_text_colour";
  DROP TYPE "enum__layouts_v_blocks_container_2_text_colour";
  DROP TYPE "enum__layouts_v_blocks_container_text_colour";`)
}
