/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'site-readers': SiteReaderAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    guides: Guide;
    'curated-lists': CuratedList;
    media: Media;
    submissions: Submission;
    properties: Property;
    locations: Location;
    specials: Special;
    reviews: Review;
    amenities: Amenity;
    'property-types': PropertyType;
    sites: Site;
    users: User;
    'site-readers': SiteReader;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'curated-lists': CuratedListsSelect<false> | CuratedListsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    specials: SpecialsSelect<false> | SpecialsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    'property-types': PropertyTypesSelect<false> | PropertyTypesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'site-readers': SiteReadersSelect<false> | SiteReadersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | SiteReader;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SiteReaderAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site?: (number | null) | Site;
  title: string;
  /**
   * URL path on the Site: "/" for Home, "/about". Filled in from the title until you change it.
   */
  path: string;
  /**
   * Tuck-In announces that this Site has joined its Client: saving the new Page fills in its Blocks with copy to edit.
   */
  template?: ('blank' | 'tuckIn') | null;
  showInNav?: boolean | null;
  /**
   * Lower comes first.
   */
  navOrder?: number | null;
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | PropertyGridBlock
        | CuratedListCardsBlock
        | CallToActionBlock
        | FAQBlock
        | FormBlock
        | AnnouncementBlock
        | AudienceBlock
        | ContactBlock
      )[]
    | null;
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  siteName?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * The Site's key. The Site deployment's SITE env var must match it, so only Super Admins can change it.
   */
  slug: string;
  /**
   * Public domain, e.g. www.example.com
   */
  domain?: string | null;
  /**
   * The rental company Awayday runs this Site for. For a Tuck-In, the company the Former Brand (this Site) joined. Used by the {client} and {client-url} Variables.
   */
  client?: {
    name?: string | null;
    website?: string | null;
  };
  /**
   * The parts of the CMS this Site uses. Pages, Media and Site Settings are always on. Turning a Section off hides it in the admin; nothing is deleted.
   */
  sections?: {
    /**
     * Properties, Locations, Specials and Reviews.
     */
    properties?: boolean | null;
    /**
     * Submissions from the Site's forms.
     */
    inbox?: boolean | null;
    /**
     * Editorial articles.
     */
    guides?: boolean | null;
    /**
     * Themed sets of Properties.
     */
    curatedLists?: boolean | null;
  };
  /**
   * Base URL of the Site deployment. The CMS sends revalidation requests here.
   */
  deploymentUrl?: string | null;
  /**
   * Shared secret for the Site deployment's revalidation endpoint. Must match the deployment's REVALIDATION_SECRET.
   */
  revalidationSecret?: string | null;
  /**
   * The Property Feed account this Site's Sync reads from.
   */
  feedAccountRef?: string | null;
  /**
   * URL patterns from the previous website, redirected to new URLs.
   */
  legacyUrls?: {
    /**
     * How the previous website addressed Property pages. Matching URLs redirect to /rentals/{slug}. Root level redirects only slugs of real Properties.
     */
    propertyPattern?: ('none' | 'cabin-rentals' | 'property-details' | 'rentals' | 'root') | null;
    /**
     * Legacy pages to redirect, e.g. /about-us.html to /about. Paths only; checked before the Property pattern.
     */
    redirects?:
      | {
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  branding?: {
    /**
     * Shown in the Site's header. One of this Site's Media files.
     */
    logo?: (number | null) | Media;
    /**
     * Hex, e.g. #1f4d3a. Header, buttons and links.
     */
    primaryColor?: string | null;
    /**
     * Hex, e.g. #d97706. Highlights and badges.
     */
    accentColor?: string | null;
    fontPairing?: ('classic' | 'modern' | 'rustic') | null;
    /**
     * A short line under the Site name, also used in page metadata.
     */
    tagline?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    social?:
      | {
          platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Which Amenities are search filters on this Site, and how they are grouped, labelled and ordered.
   */
  amenityPresentation?: {
    /**
     * The Amenities guests can filter by, in the order shown. Leave label, icon or group empty to use the Feed's.
     */
    filters?:
      | {
          amenity: number | Amenity;
          /**
           * Replaces the Amenity's name.
           */
          label?: string | null;
          /**
           * Replaces the Feed's icon key.
           */
          icon?: string | null;
          /**
           * Replaces the Feed's group.
           */
          group?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Amenities never shown on this Site, as filters or on Properties.
     */
    hidden?: (number | Amenity)[] | null;
  };
  /**
   * How this Site names each Property Type for its guests.
   */
  propertyTypeLabels?: {
    /**
     * Property Types without a label here use the Feed's name.
     */
    labels?:
      | {
          propertyType: number | PropertyType;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Check-in and check-out times, house rules, minimum age, and cancellation and deposit terms used where the Property Feed has none.
   */
  stayPolicyDefaults?: {
    /**
     * e.g. 16:00
     */
    checkIn?: string | null;
    /**
     * e.g. 10:00
     */
    checkOut?: string | null;
    /**
     * Minimum age of the lead guest.
     */
    minimumAge?: number | null;
    houseRules?: string | null;
    /**
     * Cancellation and deposit terms.
     */
    cancellationPolicy?: string | null;
  };
  /**
   * The rule that decides whether new Reviews are shown or hidden.
   */
  moderation?: {
    /**
     * New Reviews with this rating or higher are shown right away. Leave empty to hold every new Review as Pending.
     */
    autoShowMinRating?: number | null;
  };
  /**
   * Where Inquiries, Owner Leads and contact Submissions are forwarded.
   */
  forwarding?: {
    destinations?:
      | {
          kind: 'all' | 'inquiry' | 'ownerLead' | 'contact';
          type: 'webhook' | 'email';
          /**
           * Receives a JSON POST of each Submission.
           */
          url?: string | null;
          /**
           * When set, requests carry an X-Signature header: the hex HMAC-SHA256 of the body with this secret.
           */
          secret?: string | null;
          emailTo?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Write {key} in Page and Guide copy, SEO fields and links to show the value. Keys are lowercase with dashes, such as wifi-password. Built-in: {site}, {client}, {client-url}, {phone}, {email}, {domain}, {address}.
   */
  customVariables?:
    | {
        key: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site?: (number | null) | Site;
  /**
   * Describe what the image shows for people who can't see it, in a short sentence, e.g. "Hot tub on a snowy deck overlooking the mountains". Don't start with "Image of" or repeat the caption.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source, e.g. © Jane Doe
   */
  credit?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * The Awayday-wide Amenity list, mirrored from the Property Feed. Read-only here: new Amenities are added in the Feed. Each Site chooses its search filters under Sites › Properties › Amenity Presentation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  feedId: string;
  name: string;
  group?: string | null;
  /**
   * Icon key from the Feed. A Site can override it in its Amenity Presentation.
   */
  icon?: string | null;
  /**
   * Withdrawn when the Feed drops the Amenity. Sites never show withdrawn Amenities.
   */
  status?: ('active' | 'withdrawn') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The Awayday-wide Property Type list, mirrored from the Property Feed. Read-only here: new types are added in the Feed. Each Site can relabel them under Sites › Properties › Property Type labels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types".
 */
export interface PropertyType {
  id: number;
  feedId: string;
  name: string;
  /**
   * Withdrawn when the Feed drops the Property Type.
   */
  status?: ('active' | 'withdrawn') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  subheading?: string | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * A Site path like "/rentals", a full URL, or a Variable such as {client-url} or tel:{phone}.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PropertyGridBlock".
 */
export interface PropertyGridBlock {
  heading?: string | null;
  source: 'curatedList' | 'location';
  curatedList?: (number | null) | CuratedList;
  location?: (number | null) | Location;
  /**
   * Most Properties to show.
   */
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'propertyGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curated-lists".
 */
export interface CuratedList {
  id: number;
  site?: (number | null) | Site;
  title: string;
  /**
   * Part of the public URL. Set once when created; changing it changes the URL.
   */
  slug?: string | null;
  /**
   * Order of the Properties in the list. Empty: Featured.
   */
  sort?: ('featured' | 'rating' | 'sleeps' | 'bedrooms' | 'name') | null;
  heroImage?: (number | null) | Media;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Properties that match every condition set here are in the list. Members update as the Sync runs.
   */
  rule?: {
    /**
     * This Location or any Location inside it.
     */
    location?: (number | null) | Location;
    /**
     * Has all of these Amenities.
     */
    amenities?: (number | Amenity)[] | null;
    /**
     * Is any of these Property Types.
     */
    propertyTypes?: (number | PropertyType)[] | null;
    minBedrooms?: number | null;
    minSleeps?: number | null;
    /**
     * Only Properties that allow pets. Unticked: any.
     */
    petsAllowed?: boolean | null;
  };
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  siteName?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  site?: (number | null) | Site;
  /**
   * Parent › Name (Location Level). Set automatically.
   */
  adminTitle?: string | null;
  /**
   * Display name, or the Feed name. Set automatically.
   */
  title?: string | null;
  /**
   * Shown to guests instead of the Feed name. Leave empty to use the Feed name.
   */
  displayName?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  /**
   * What the Properties in this Complex share. Shown on the Complex page.
   */
  complex?: {
    address?: string | null;
    sharedAmenities?: (number | Amenity)[] | null;
    checkInInfo?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    housekeeping?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    feeNotes?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  feedId: string;
  /**
   * The node name in the PMS.
   */
  name: string;
  /**
   * The node type in the PMS. For reference only; the Location Level decides how it appears.
   */
  feedType?: string | null;
  /**
   * The parent node in the PMS.
   */
  parent?: (number | null) | Location;
  /**
   * How this Location appears in navigation, search and URLs. Independent of the PMS node type.
   */
  level?: ('destination' | 'area' | 'complex') | null;
  /**
   * Part of the public URL. Set once when created; changing it changes the URL.
   */
  slug?: string | null;
  /**
   * Shown to guests on the Site.
   */
  visible?: boolean | null;
  /**
   * Follows the Feed node. Withdrawn Locations are hidden from guests.
   */
  status: 'active' | 'withdrawn';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CuratedListCardsBlock".
 */
export interface CuratedListCardsBlock {
  heading?: string | null;
  lists: (number | CuratedList)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'curatedListCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  button?: {
    label?: string | null;
    /**
     * A Site path like "/rentals", a full URL, or a Variable such as {client-url} or tel:{phone}.
     */
    href?: string | null;
  };
  style: 'primary' | 'secondary' | 'inverted';
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Booking inquiries ask for dates and guests, and name the Property when the page is opened with ?property=<slug>. Owner leads ask about the owner's home.
   */
  kind: 'inquiry' | 'ownerLead' | 'contact';
  submitLabel?: string | null;
  /**
   * Shown once the form is sent. Leave empty for the default.
   */
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementBlock".
 */
export interface AnnouncementBlock {
  headline: string;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'announcement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock".
 */
export interface AudienceBlock {
  title: string;
  audience: 'owners' | 'guests';
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  points?:
    | {
        title: string;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  cta?: {
    label?: string | null;
    /**
     * A Site path like "/rentals", a full URL, or a Variable such as {client-url} or tel:{phone}.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'audience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  title: string;
  /**
   * Shown before the phone and email.
   */
  text?: string | null;
  /**
   * Usually {phone}, from Site Settings.
   */
  phone?: string | null;
  /**
   * Usually {email}, from Site Settings.
   */
  email?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  site?: (number | null) | Site;
  title: string;
  /**
   * Part of the public URL. Set once when created; changing it changes the URL.
   */
  slug?: string | null;
  /**
   * Set when first published. Used to order Guides.
   */
  publishedAt?: string | null;
  locations?: (number | Location)[] | null;
  properties?: (number | Property)[] | null;
  /**
   * A short summary for Guide lists and cards.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  siteName?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  site?: (number | null) | Site;
  /**
   * The Headline, or the feed name. Set automatically.
   */
  adminTitle?: string | null;
  /**
   * Follows the Feed Listing. Withdrawn Properties are hidden but kept intact.
   */
  status: 'active' | 'withdrawn';
  /**
   * Part of the public URL. Set once when created; changing it changes the URL.
   */
  slug?: string | null;
  /**
   * Highlight this Property on the Site.
   */
  featured?: boolean | null;
  /**
   * Shown instead of the feed name when set.
   */
  headline?: string | null;
  /**
   * A short teaser for cards and search results.
   */
  summary?: string | null;
  /**
   * Shown instead of the feed description when set.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  feedId: string;
  /**
   * The listing name from the Property Feed.
   */
  feedName?: string | null;
  location?: (number | null) | Location;
  propertyType?: (number | null) | PropertyType;
  amenities?: (number | Amenity)[] | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  sleeps?: number | null;
  petsAllowed?: boolean | null;
  /**
   * Average of shown Reviews.
   */
  rating?: number | null;
  reviewCount?: number | null;
  /**
   * The Property Feed's description. The Site shows it when the Editorial description is empty.
   */
  feedDescription?: string | null;
  onlineBookable?: boolean | null;
  /**
   * When the Property Feed last changed this listing.
   */
  feedUpdatedAt?: string | null;
  virtualTourUrl?: string | null;
  /**
   * Feed photo URLs, in order. Never uploaded to Media (ADR-0008).
   */
  photos?:
    | {
        url: string;
        caption?: string | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  address?: {
    line1?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  rooms?:
    | {
        name?: string | null;
        sleeps?: number | null;
        beds?:
          | {
              /**
               * e.g. king, queen, bunk
               */
              type: string;
              count?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Empty fields fall back to the Site's Default Stay Policy.
   */
  stayPolicy?: {
    /**
     * e.g. 16:00
     */
    checkIn?: string | null;
    /**
     * e.g. 10:00
     */
    checkOut?: string | null;
    /**
     * Minimum age of the lead guest.
     */
    minimumAge?: number | null;
    houseRules?: string | null;
    /**
     * Cancellation and deposit terms.
     */
    cancellationPolicy?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  site: number | Site;
  kind: 'inquiry' | 'ownerLead' | 'contact';
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  property?: (number | null) | Property;
  arrival?: string | null;
  departure?: string | null;
  guests?: number | null;
  /**
   * Any other form fields, as sent by the Site.
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The page the form was sent from.
   */
  sourceUrl?: string | null;
  website?: string | null;
  forwardingStatus: 'pending' | 'sent' | 'failed';
  forwardingAttempts?: number | null;
  forwardedAt?: string | null;
  lastForwardingError?: string | null;
  deliveredTo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  retainUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specials".
 */
export interface Special {
  id: number;
  site?: (number | null) | Site;
  /**
   * The public title, or the promo code. Set automatically.
   */
  adminTitle?: string | null;
  /**
   * Follows the Property Feed. Withdrawn Specials are hidden.
   */
  status: 'active' | 'withdrawn';
  /**
   * Guests see it only while it is also Active and not expired.
   */
  showOnSite?: boolean | null;
  /**
   * Public title on the Site.
   */
  title?: string | null;
  /**
   * Part of the public URL. Set once when created; changing it changes the URL.
   */
  slug?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  disclaimer?: string | null;
  heroImage?: (number | null) | Media;
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the document title.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  feedId: string;
  code?: string | null;
  validFrom?: string | null;
  /**
   * Hidden from guests after this date.
   */
  validTo?: string | null;
  /**
   * The Feed's description of the discount.
   */
  discountSummary?: string | null;
  properties?: (number | Property)[] | null;
  terms?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  site?: (number | null) | Site;
  /**
   * Rating, guest and Property. Set automatically.
   */
  adminTitle?: string | null;
  /**
   * Only shown Reviews appear on the Site and count in the Rating. Pending Reviews wait for a decision.
   */
  moderation: 'pending' | 'shown' | 'hidden';
  /**
   * Follows the Property Feed. Withdrawn Reviews are hidden.
   */
  status: 'active' | 'withdrawn';
  feedId: string;
  source?: string | null;
  property?: (number | null) | Property;
  rating?: number | null;
  stayDate?: string | null;
  /**
   * Display name only.
   */
  guestName?: string | null;
  title?: string | null;
  body?: string | null;
  managerResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  /**
   * Not limited by Site Assignment.
   */
  superAdmin?: boolean | null;
  /**
   * Set on first Microsoft sign-in.
   */
  entraOid?: string | null;
  /**
   * The Sites this Staff User can access.
   */
  tenants?:
    | {
        site: number | Site;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys for Site deployments. Each can read only its own Site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-readers".
 */
export interface SiteReader {
  id: number;
  /**
   * e.g. demo-beach production
   */
  name?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  collection: 'site-readers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'curated-lists';
        value: number | CuratedList;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'specials';
        value: number | Special;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'property-types';
        value: number | PropertyType;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'site-readers';
        value: number | SiteReader;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'site-readers';
        value: number | SiteReader;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'site-readers';
        value: number | SiteReader;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  path?: T;
  template?: T;
  showInNav?: T;
  navOrder?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        propertyGrid?: T | PropertyGridBlockSelect<T>;
        curatedListCards?: T | CuratedListCardsBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        announcement?: T | AnnouncementBlockSelect<T>;
        audience?: T | AudienceBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  siteName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PropertyGridBlock_select".
 */
export interface PropertyGridBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  curatedList?: T;
  location?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CuratedListCardsBlock_select".
 */
export interface CuratedListCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  lists?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  kind?: T;
  submitLabel?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementBlock_select".
 */
export interface AnnouncementBlockSelect<T extends boolean = true> {
  headline?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock_select".
 */
export interface AudienceBlockSelect<T extends boolean = true> {
  title?: T;
  audience?: T;
  intro?: T;
  points?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  closing?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  phone?: T;
  email?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  publishedAt?: T;
  locations?: T;
  properties?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  siteName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curated-lists_select".
 */
export interface CuratedListsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  sort?: T;
  heroImage?: T;
  intro?: T;
  rule?:
    | T
    | {
        location?: T;
        amenities?: T;
        propertyTypes?: T;
        minBedrooms?: T;
        minSleeps?: T;
        petsAllowed?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  siteName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  site?: T;
  kind?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  property?: T;
  arrival?: T;
  departure?: T;
  guests?: T;
  payload?: T;
  sourceUrl?: T;
  website?: T;
  forwardingStatus?: T;
  forwardingAttempts?: T;
  forwardedAt?: T;
  lastForwardingError?: T;
  deliveredTo?: T;
  retainUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  site?: T;
  adminTitle?: T;
  status?: T;
  slug?: T;
  featured?: T;
  headline?: T;
  summary?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  feedId?: T;
  feedName?: T;
  location?: T;
  propertyType?: T;
  amenities?: T;
  bedrooms?: T;
  bathrooms?: T;
  sleeps?: T;
  petsAllowed?: T;
  rating?: T;
  reviewCount?: T;
  feedDescription?: T;
  onlineBookable?: T;
  feedUpdatedAt?: T;
  virtualTourUrl?: T;
  photos?:
    | T
    | {
        url?: T;
        caption?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  address?:
    | T
    | {
        line1?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  rooms?:
    | T
    | {
        name?: T;
        sleeps?: T;
        beds?:
          | T
          | {
              type?: T;
              count?: T;
              id?: T;
            };
        id?: T;
      };
  stayPolicy?:
    | T
    | {
        checkIn?: T;
        checkOut?: T;
        minimumAge?: T;
        houseRules?: T;
        cancellationPolicy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  site?: T;
  adminTitle?: T;
  title?: T;
  displayName?: T;
  intro?: T;
  heroImage?: T;
  complex?:
    | T
    | {
        address?: T;
        sharedAmenities?: T;
        checkInInfo?: T;
        housekeeping?: T;
        feeNotes?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  feedId?: T;
  name?: T;
  feedType?: T;
  parent?: T;
  level?: T;
  slug?: T;
  visible?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specials_select".
 */
export interface SpecialsSelect<T extends boolean = true> {
  site?: T;
  adminTitle?: T;
  status?: T;
  showOnSite?: T;
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  disclaimer?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  feedId?: T;
  code?: T;
  validFrom?: T;
  validTo?: T;
  discountSummary?: T;
  properties?: T;
  terms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  site?: T;
  adminTitle?: T;
  moderation?: T;
  status?: T;
  feedId?: T;
  source?: T;
  property?: T;
  rating?: T;
  stayDate?: T;
  guestName?: T;
  title?: T;
  body?: T;
  managerResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  feedId?: T;
  name?: T;
  group?: T;
  icon?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types_select".
 */
export interface PropertyTypesSelect<T extends boolean = true> {
  feedId?: T;
  name?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  client?:
    | T
    | {
        name?: T;
        website?: T;
      };
  sections?:
    | T
    | {
        properties?: T;
        inbox?: T;
        guides?: T;
        curatedLists?: T;
      };
  deploymentUrl?: T;
  revalidationSecret?: T;
  feedAccountRef?: T;
  legacyUrls?:
    | T
    | {
        propertyPattern?: T;
        redirects?:
          | T
          | {
              from?: T;
              to?: T;
              id?: T;
            };
      };
  branding?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
        accentColor?: T;
        fontPairing?: T;
        tagline?: T;
        phone?: T;
        email?: T;
        address?: T;
        social?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  amenityPresentation?:
    | T
    | {
        filters?:
          | T
          | {
              amenity?: T;
              label?: T;
              icon?: T;
              group?: T;
              id?: T;
            };
        hidden?: T;
      };
  propertyTypeLabels?:
    | T
    | {
        labels?:
          | T
          | {
              propertyType?: T;
              label?: T;
              id?: T;
            };
      };
  stayPolicyDefaults?:
    | T
    | {
        checkIn?: T;
        checkOut?: T;
        minimumAge?: T;
        houseRules?: T;
        cancellationPolicy?: T;
      };
  moderation?:
    | T
    | {
        autoShowMinRating?: T;
      };
  forwarding?:
    | T
    | {
        destinations?:
          | T
          | {
              kind?: T;
              type?: T;
              url?: T;
              secret?: T;
              emailTo?: T;
              id?: T;
            };
      };
  customVariables?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  superAdmin?: T;
  entraOid?: T;
  tenants?:
    | T
    | {
        site?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-readers_select".
 */
export interface SiteReadersSelect<T extends boolean = true> {
  name?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
