/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    layouts: Layout;
    media: Media;
    fonts: Font;
    'font-files': FontFile;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    layouts: LayoutsSelect<false> | LayoutsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    fonts: FontsSelect<false> | FontsSelect<true>;
    'font-files': FontFilesSelect<false> | FontFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    brand: Brand;
    seo: Seo;
    theme: Theme;
  };
  globalsSelect: {
    brand: BrandSelect<false> | BrandSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path on the Site: "/" for Home, "/about". Filled in from the title when left empty.
   */
  path: string;
  blocks?:
    | (
        | HeroBlock
        | SearchHeroBlock
        | RichTextBlock
        | CallToActionBlock
        | FeaturedRentalsBlock
        | LargeGroupRentalsBlock
        | RentalGridBlock
        | StepsBlock
        | FeaturesBlock
        | AmenitiesBlock
        | StatsBlock
        | ImageTextBlock
        | TestimonialsBlock
        | TrustStripBlock
        | OwnerBandBlock
        | NewsletterBlock
        | BlogTeaserBlock
        | LocationBlock
        | FaqBlock
        | FormBlock
        | ButtonBlock
        | ImageBlock
        | ContainerBlock
      )[]
    | null;
  layout?: {
    mode?: ('route' | 'specific' | 'none') | null;
    layout?: (number | null) | Layout;
  };
  seo?: {
    /**
     * Shown in search results and the browser tab. Defaults to the Page title. Up to 60 characters.
     */
    title?: string | null;
    /**
     * The summary shown under the title in search results. Up to 160 characters.
     */
    description?: string | null;
    /**
     * Shown when the Page is shared on social media.
     */
    image?: (number | null) | Media;
  };
  /**
   * New Pages can start from a copy of this Page. A Page Template is never published.
   */
  isTemplate?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * A short line above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * A word or phrase from the heading, shown in the accent style.
   */
  accentWord?: string | null;
  subheading?: string | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  /**
   * Optional. Fused to the foot of the Hero.
   */
  trustStrip?:
    | {
        /**
         * Optional, such as "4.9".
         */
        stat?: string | null;
        text: string;
        /**
         * A Lucide icon name, such as "wifi" or "map-pin".
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows for people who can't see it, in a short sentence. Don't start with "Image of".
   */
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  /**
   * Photographer or source, e.g. © Jane Doe
   */
  credit?: string | null;
  /**
   * For stock photos: who took it, where it came from.
   */
  attribution?: {
    author?: string | null;
    sourceUrl?: string | null;
    licence?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SearchHeroBlock".
 */
export interface SearchHeroBlock {
  /**
   * A short line above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * A word or phrase from the heading, shown in the accent style.
   */
  accentWord?: string | null;
  subheading?: string | null;
  image?: (number | null) | Media;
  searchLabel: string;
  /**
   * Optional places to suggest in the search.
   */
  locations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'searchHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('reading' | 'wide') | null;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  button?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  style: 'primary' | 'secondary' | 'inverted' | 'dark';
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedRentalsBlock".
 */
export interface FeaturedRentalsBlock {
  heading: string;
  /**
   * How many Rentals to show.
   */
  count: number;
  variant: 'carousel' | 'grid';
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredRentals';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LargeGroupRentalsBlock".
 */
export interface LargeGroupRentalsBlock {
  heading: string;
  /**
   * Shows the Rentals that sleep at least this many guests.
   */
  minSleeps: number;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'largeGroupRentals';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RentalGridBlock".
 */
export interface RentalGridBlock {
  heading: string;
  /**
   * How many Rentals each page shows.
   */
  pageSize: number;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rentalGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  heading: string;
  intro?: string | null;
  steps: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  heading: string;
  intro?: string | null;
  features: {
    /**
     * A Lucide icon name, such as "wifi" or "map-pin".
     */
    icon: string;
    title: string;
    text: string;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock".
 */
export interface AmenitiesBlock {
  heading: string;
  intro?: string | null;
  variant: 'mosaic' | 'icons';
  items: {
    label: string;
    /**
     * The tile's photo, for the mosaic.
     */
    image?: (number | null) | Media;
    /**
     * The icon, for the icon list, such as "wifi".
     */
    icon?: string | null;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'amenities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading: string;
  stats: {
    /**
     * The figure, such as "4.9" or "120+".
     */
    value: string;
    label: string;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  heading: string;
  text?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional. Shown with the image.
   */
  caption?: string | null;
  imageSide: 'left' | 'right';
  /**
   * Optional. A short list, each with an icon.
   */
  points?:
    | {
        /**
         * A Lucide icon name, such as "wifi" or "map-pin".
         */
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading: string;
  variant: 'carousel' | 'grid';
  testimonials: {
    quote: string;
    name: string;
    /**
     * Under the name, such as "Stayed for a week in June".
     */
    role: string;
    /**
     * From 1 to 5 stars.
     */
    rating: number;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStripBlock".
 */
export interface TrustStripBlock {
  /**
   * Optional. A line to introduce the strip.
   */
  heading?: string | null;
  variant: 'items' | 'logos';
  items?:
    | {
        /**
         * Optional, such as "4.9".
         */
        stat?: string | null;
        text: string;
        /**
         * A Lucide icon name, such as "wifi" or "map-pin".
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  logos?:
    | {
        /**
         * The partner's name, read out for the logo.
         */
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerBandBlock".
 */
export interface OwnerBandBlock {
  heading: string;
  pitch?: string | null;
  benefits: {
    text: string;
    id?: string | null;
  }[];
  cta?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ownerBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  heading: string;
  text?: string | null;
  emailPlaceholder?: string | null;
  buttonLabel: string;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogTeaserBlock".
 */
export interface BlogTeaserBlock {
  heading: string;
  /**
   * Optional. Shown when it has a label and a link.
   */
  allPostsLink?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blogTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlock".
 */
export interface LocationBlock {
  heading: string;
  address: string;
  text?: string | null;
  map: 'card' | 'image';
  /**
   * A picture of the map. Its alt text is read out for it.
   */
  mapImage?: (number | null) | Media;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'location';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: string;
  questions: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  heading: string;
  intro?: string | null;
  /**
   * The fields the form shows, in this order.
   */
  formFields: ('name' | 'email' | 'phone' | 'message' | 'propertyAddress' | 'dates')[];
  submitLabel: string;
  successMessage: string;
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  link?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  style: 'primary' | 'accent' | 'outline';
  align: 'start' | 'centre' | 'end';
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image?: (number | null) | Media;
  /**
   * Optional. Shown under the image.
   */
  caption?: string | null;
  aspect: 'original' | '16x9' | '4x3' | '1x1';
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlock".
 */
export interface ContainerBlock {
  columns: '1' | '2' | '3' | '4';
  gap: 'small' | 'medium' | 'large';
  align: 'top' | 'centre' | 'stretch';
  width: 'page' | 'reading';
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  children?:
    | (
        | HeroBlock
        | SearchHeroBlock
        | RichTextBlock
        | CallToActionBlock
        | FeaturedRentalsBlock
        | LargeGroupRentalsBlock
        | RentalGridBlock
        | StepsBlock
        | FeaturesBlock
        | AmenitiesBlock
        | StatsBlock
        | ImageTextBlock
        | TestimonialsBlock
        | TrustStripBlock
        | OwnerBandBlock
        | NewsletterBlock
        | BlogTeaserBlock
        | LocationBlock
        | FaqBlock
        | FormBlock
        | ButtonBlock
        | ImageBlock
        | ContainerBlockLevel2
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlockLevel2".
 */
export interface ContainerBlockLevel2 {
  columns: '1' | '2' | '3' | '4';
  gap: 'small' | 'medium' | 'large';
  align: 'top' | 'centre' | 'stretch';
  width: 'page' | 'reading';
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  children?:
    | (
        | HeroBlock
        | SearchHeroBlock
        | RichTextBlock
        | CallToActionBlock
        | FeaturedRentalsBlock
        | LargeGroupRentalsBlock
        | RentalGridBlock
        | StepsBlock
        | FeaturesBlock
        | AmenitiesBlock
        | StatsBlock
        | ImageTextBlock
        | TestimonialsBlock
        | TrustStripBlock
        | OwnerBandBlock
        | NewsletterBlock
        | BlogTeaserBlock
        | LocationBlock
        | FaqBlock
        | FormBlock
        | ButtonBlock
        | ImageBlock
        | ContainerBlockLevel3
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlockLevel3".
 */
export interface ContainerBlockLevel3 {
  columns: '1' | '2' | '3' | '4';
  gap: 'small' | 'medium' | 'large';
  align: 'top' | 'centre' | 'stretch';
  width: 'page' | 'reading';
  background?: ('default' | 'muted' | 'primary' | 'dark') | null;
  children?:
    | (
        | HeroBlock
        | SearchHeroBlock
        | RichTextBlock
        | CallToActionBlock
        | FeaturedRentalsBlock
        | LargeGroupRentalsBlock
        | RentalGridBlock
        | StepsBlock
        | FeaturesBlock
        | AmenitiesBlock
        | StatsBlock
        | ImageTextBlock
        | TestimonialsBlock
        | TrustStripBlock
        | OwnerBandBlock
        | NewsletterBlock
        | BlogTeaserBlock
        | LocationBlock
        | FaqBlock
        | FormBlock
        | ButtonBlock
        | ImageBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts".
 */
export interface Layout {
  id: number;
  name: string;
  header?: (LogoBlock | NavigationBlock | HeaderActionsBlock | UtilityStripBlock)[] | null;
  footer?: (FooterColumnsBlock | LegalBarBlock | NewsletterBlock | CallToActionBlock)[] | null;
  /**
   * Pages at or under these paths use this Layout, like "/stays". The longest match wins. A path belongs to one Layout.
   */
  paths?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pages that no path or choice covers use the default. There is always exactly one: making another Layout the default clears this one.
   */
  isDefault?: boolean | null;
  /**
   * Optional. Replaces the automatic summary of this save in the history.
   */
  note?: string | null;
  changeSummary?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoBlock".
 */
export interface LogoBlock {
  size: 'small' | 'medium' | 'large';
  showTagline?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationBlock".
 */
export interface NavigationBlock {
  items?:
    | {
        label: string;
        link?: {
          type?: ('page' | 'url') | null;
          page?: (number | null) | Page;
          /**
           * A Site path like "/about", or a full URL.
           */
          url?: string | null;
        };
        display?: ('dropdown' | 'mega') | null;
        /**
         * Add links to make this item a dropdown. A dropdown holds links only.
         */
        children?:
          | {
              label: string;
              link?: {
                type?: ('page' | 'url') | null;
                page?: (number | null) | Page;
                /**
                 * A Site path like "/about", or a full URL.
                 */
                url?: string | null;
              };
              /**
               * Mega-menu only: links with the same heading share a column.
               */
              column?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'navigation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderActionsBlock".
 */
export interface HeaderActionsBlock {
  showPhone?: boolean | null;
  /**
   * Leave empty to show the Brand's phone number.
   */
  phone?: string | null;
  button?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  login?: {
    label?: string | null;
    /**
     * A Site path like "/about", or a full URL.
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'headerActions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UtilityStripBlock".
 */
export interface UtilityStripBlock {
  /**
   * A short line, such as an offer or a notice.
   */
  text: string;
  links?:
    | {
        label: string;
        link?: {
          type?: ('page' | 'url') | null;
          page?: (number | null) | Page;
          /**
           * A Site path like "/about", or a full URL.
           */
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'utilityStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnsBlock".
 */
export interface FooterColumnsBlock {
  columns?:
    | {
        heading: string;
        /**
         * The address and social links come from the Brand unless you override the address here.
         */
        content: 'links' | 'address' | 'hours' | 'social';
        links?:
          | {
              label: string;
              link?: {
                type?: ('page' | 'url') | null;
                page?: (number | null) | Page;
                /**
                 * A Site path like "/about", or a full URL.
                 */
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        /**
         * Leave empty to show the Brand's address.
         */
        address?: string | null;
        /**
         * One line per day or range, such as Mon–Fri 9:00–17:00.
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalBarBlock".
 */
export interface LegalBarBlock {
  /**
   * {year} becomes the current year and {name} the Brand's name.
   */
  text: string;
  links?:
    | {
        label: string;
        link?: {
          type?: ('page' | 'url') | null;
          page?: (number | null) | Page;
          /**
           * A Site path like "/about", or a full URL.
           */
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'legalBar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * From Entra ID.
   */
  email: string;
  name?: string | null;
  entraOid: string;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts".
 */
export interface Font {
  id: number;
  /**
   * The name the Theme shows, and the CSS font-family. For a Google Font, its name on Google Fonts.
   */
  family: string;
  kind: 'serif' | 'sans' | 'slab';
  /**
   * Where the files came from.
   */
  source?: ('uploaded' | 'google') | null;
  files: {
    weight: number;
    style: 'normal' | 'italic';
    file: number | FontFile;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font-files".
 */
export interface FontFile {
  id: number;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'layouts';
        value: number | Layout;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'fonts';
        value: number | Font;
      } | null)
    | ({
        relationTo: 'font-files';
        value: number | FontFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  blocks?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        searchHero?: T | SearchHeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        featuredRentals?: T | FeaturedRentalsBlockSelect<T>;
        largeGroupRentals?: T | LargeGroupRentalsBlockSelect<T>;
        rentalGrid?: T | RentalGridBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        trustStrip?: T | TrustStripBlockSelect<T>;
        ownerBand?: T | OwnerBandBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        blogTeaser?: T | BlogTeaserBlockSelect<T>;
        location?: T | LocationBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        button?: T | ButtonBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        container?: T | ContainerBlockSelect<T>;
      };
  layout?:
    | T
    | {
        mode?: T;
        layout?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  isTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  accentWord?: T;
  subheading?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  trustStrip?:
    | T
    | {
        stat?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SearchHeroBlock_select".
 */
export interface SearchHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  accentWord?: T;
  subheading?: T;
  image?: T;
  searchLabel?: T;
  locations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  style?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedRentalsBlock_select".
 */
export interface FeaturedRentalsBlockSelect<T extends boolean = true> {
  heading?: T;
  count?: T;
  variant?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LargeGroupRentalsBlock_select".
 */
export interface LargeGroupRentalsBlockSelect<T extends boolean = true> {
  heading?: T;
  minSleeps?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RentalGridBlock_select".
 */
export interface RentalGridBlockSelect<T extends boolean = true> {
  heading?: T;
  pageSize?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AmenitiesBlock_select".
 */
export interface AmenitiesBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  variant?: T;
  items?:
    | T
    | {
        label?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  image?: T;
  caption?: T;
  imageSide?: T;
  points?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  variant?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        rating?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStripBlock_select".
 */
export interface TrustStripBlockSelect<T extends boolean = true> {
  heading?: T;
  variant?: T;
  items?:
    | T
    | {
        stat?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  logos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OwnerBandBlock_select".
 */
export interface OwnerBandBlockSelect<T extends boolean = true> {
  heading?: T;
  pitch?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  emailPlaceholder?: T;
  buttonLabel?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogTeaserBlock_select".
 */
export interface BlogTeaserBlockSelect<T extends boolean = true> {
  heading?: T;
  allPostsLink?:
    | T
    | {
        label?: T;
        href?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlock_select".
 */
export interface LocationBlockSelect<T extends boolean = true> {
  heading?: T;
  address?: T;
  text?: T;
  map?: T;
  mapImage?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  formFields?: T;
  submitLabel?: T;
  successMessage?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock_select".
 */
export interface ButtonBlockSelect<T extends boolean = true> {
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  style?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  aspect?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlock_select".
 */
export interface ContainerBlockSelect<T extends boolean = true> {
  columns?: T;
  gap?: T;
  align?: T;
  width?: T;
  background?: T;
  children?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        searchHero?: T | SearchHeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        featuredRentals?: T | FeaturedRentalsBlockSelect<T>;
        largeGroupRentals?: T | LargeGroupRentalsBlockSelect<T>;
        rentalGrid?: T | RentalGridBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        trustStrip?: T | TrustStripBlockSelect<T>;
        ownerBand?: T | OwnerBandBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        blogTeaser?: T | BlogTeaserBlockSelect<T>;
        location?: T | LocationBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        button?: T | ButtonBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        container?: T | ContainerBlockLevel2Select<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlockLevel2_select".
 */
export interface ContainerBlockLevel2Select<T extends boolean = true> {
  columns?: T;
  gap?: T;
  align?: T;
  width?: T;
  background?: T;
  children?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        searchHero?: T | SearchHeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        featuredRentals?: T | FeaturedRentalsBlockSelect<T>;
        largeGroupRentals?: T | LargeGroupRentalsBlockSelect<T>;
        rentalGrid?: T | RentalGridBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        trustStrip?: T | TrustStripBlockSelect<T>;
        ownerBand?: T | OwnerBandBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        blogTeaser?: T | BlogTeaserBlockSelect<T>;
        location?: T | LocationBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        button?: T | ButtonBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        container?: T | ContainerBlockLevel3Select<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlockLevel3_select".
 */
export interface ContainerBlockLevel3Select<T extends boolean = true> {
  columns?: T;
  gap?: T;
  align?: T;
  width?: T;
  background?: T;
  children?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        searchHero?: T | SearchHeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        featuredRentals?: T | FeaturedRentalsBlockSelect<T>;
        largeGroupRentals?: T | LargeGroupRentalsBlockSelect<T>;
        rentalGrid?: T | RentalGridBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        amenities?: T | AmenitiesBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        trustStrip?: T | TrustStripBlockSelect<T>;
        ownerBand?: T | OwnerBandBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        blogTeaser?: T | BlogTeaserBlockSelect<T>;
        location?: T | LocationBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        button?: T | ButtonBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts_select".
 */
export interface LayoutsSelect<T extends boolean = true> {
  name?: T;
  header?:
    | T
    | {
        logo?: T | LogoBlockSelect<T>;
        navigation?: T | NavigationBlockSelect<T>;
        headerActions?: T | HeaderActionsBlockSelect<T>;
        utilityStrip?: T | UtilityStripBlockSelect<T>;
      };
  footer?:
    | T
    | {
        footerColumns?: T | FooterColumnsBlockSelect<T>;
        legalBar?: T | LegalBarBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
      };
  paths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  isDefault?: T;
  note?: T;
  changeSummary?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoBlock_select".
 */
export interface LogoBlockSelect<T extends boolean = true> {
  size?: T;
  showTagline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationBlock_select".
 */
export interface NavigationBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
            };
        display?: T;
        children?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                  };
              column?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderActionsBlock_select".
 */
export interface HeaderActionsBlockSelect<T extends boolean = true> {
  showPhone?: T;
  phone?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  login?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UtilityStripBlock_select".
 */
export interface UtilityStripBlockSelect<T extends boolean = true> {
  text?: T;
  links?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnsBlock_select".
 */
export interface FooterColumnsBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        content?: T;
        links?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
            };
        address?: T;
        hours?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalBarBlock_select".
 */
export interface LegalBarBlockSelect<T extends boolean = true> {
  text?: T;
  links?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  _objectKey?: T;
  credit?: T;
  attribution?:
    | T
    | {
        author?: T;
        sourceUrl?: T;
        licence?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts_select".
 */
export interface FontsSelect<T extends boolean = true> {
  family?: T;
  kind?: T;
  source?: T;
  files?:
    | T
    | {
        weight?: T;
        style?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font-files_select".
 */
export interface FontFilesSelect<T extends boolean = true> {
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  entraOid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * A short line under the Site name.
   */
  tagline?: string | null;
  /**
   * Shown in the Site's header.
   */
  logo?: (number | null) | Media;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * How Page titles read in search results and the browser tab. %s is the Page title and {name} is the Site name.
   */
  titlePattern?: string | null;
  /**
   * Used for Pages that have no SEO description of their own.
   */
  description?: string | null;
  /**
   * Shown when a Page without its own SEO image is shared on social media.
   */
  image?: (number | null) | Media;
  /**
   * The icon in browser tabs. A square PNG works best.
   */
  favicon?: (number | null) | Media;
  /**
   * Off adds noindex to every page and makes robots.txt disallow everything.
   */
  allowIndexing?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  primary: string;
  accent: string;
  /**
   * Optional. Leave empty for a two-colour Theme.
   */
  third?: string | null;
  /**
   * The ink: body and heading text.
   */
  text: string;
  /**
   * Dark bands. Leave empty to derive it from the text colour.
   */
  darkSurface?: string | null;
  neutralTint: 'neutral' | 'warm' | 'cool' | 'brand';
  /**
   * A built-in font (built-in:<family>) or a stored Font (font:<id>). The Theme editor picks it from a list.
   */
  headingFont: string;
  /**
   * A built-in font (built-in:<family>) or a stored Font (font:<id>). The Theme editor picks it from a list.
   */
  bodyFont: string;
  headingWeight: 'regular' | 'medium' | 'bold' | 'black';
  headingCase: 'normal' | 'uppercase';
  buttonCorners: 'square' | 'soft' | 'rounded' | 'pill';
  cardCorners: 'square' | 'soft' | 'rounded';
  spacing: 'compact' | 'comfortable' | 'spacious';
  shadows: 'none' | 'subtle' | 'lifted';
  /**
   * Style applies to primary buttons. The accent button stays filled.
   */
  buttonStyle: 'solid' | 'outline';
  buttonLetters: 'normal' | 'uppercase' | 'title';
  buttonWeight: 'regular' | 'medium' | 'bold';
  motion: 'none' | 'subtle' | 'lively';
  /**
   * Optional. Replaces the automatic summary of this save in the history.
   */
  note?: string | null;
  changeSummary?: string | null;
  updatedBy?: (number | null) | User;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  logo?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  titlePattern?: T;
  description?: T;
  image?: T;
  favicon?: T;
  allowIndexing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  primary?: T;
  accent?: T;
  third?: T;
  text?: T;
  darkSurface?: T;
  neutralTint?: T;
  headingFont?: T;
  bodyFont?: T;
  headingWeight?: T;
  headingCase?: T;
  buttonCorners?: T;
  cardCorners?: T;
  spacing?: T;
  shadows?: T;
  buttonStyle?: T;
  buttonLetters?: T;
  buttonWeight?: T;
  motion?: T;
  note?: T;
  changeSummary?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}