import type { CollectionConfig } from "payload"

import { activeForReader, staffOfSite, syncOnly } from "../../access"
import { revalidationHooks, tagPresets } from "../../revalidation"
import { slugField } from "../../fields/slug"
import { propertyAdminTitleField } from "./adminTitle"
import { editorialFields } from "./editorial"
import { factsFields, statusField } from "./facts"

/**
 * A vacation rental on one Site, created and withdrawn only by the Sync
 * (ADR-0001, ADR-0002). Property Facts (./facts.ts) are read-only; Staff Users
 * edit Editorial Content (./editorial.ts). No Draft state: Active Properties
 * are live, and Withdrawn ones keep everything. One Property per
 * (Site, Feed ID).
 *
 * Sidebar fields are top-level because Payload only renders top-level fields
 * in the sidebar: `status` is a Property Fact; `slug` and `featured` are
 * Editorial Content. The slug is set once from the feed name and never
 * regenerated by the Sync. `adminTitle` (./adminTitle.ts) names the Property
 * in lists and pickers: its Headline, else its feed name.
 */
export const Properties: CollectionConfig = {
  slug: "properties",
  admin: {
    useAsTitle: "adminTitle",
    defaultColumns: [
      "adminTitle",
      "feedName",
      "location",
      "status",
      "featured",
    ],
    listSearchableFields: ["adminTitle", "feedName", "headline", "feedId"],
    pagination: { defaultLimit: 50 },
    group: "Properties",
  },
  access: {
    create: syncOnly,
    read: activeForReader,
    update: staffOfSite,
    delete: syncOnly,
    unlock: staffOfSite,
  },
  hooks: revalidationHooks(tagPresets.properties),
  indexes: [
    { fields: ["site", "feedId"], unique: true },
    { fields: ["site", "slug"], unique: true },
  ],
  fields: [
    propertyAdminTitleField,
    statusField,
    slugField({ from: "feedName" }),
    {
      name: "featured",
      type: "checkbox",
      defaultValue: false,
      admin: {
        position: "sidebar",
        description: "Highlight this Property on the Site.",
        components: {
          Cell: "/collections/Properties/admin/YesNoCell#YesNoCell",
        },
      },
    },
    {
      type: "tabs",
      tabs: [
        {
          label: "Editorial",
          description: "Written in the CMS. The Sync never overwrites it.",
          fields: editorialFields,
        },
        {
          label: "Feed facts",
          description:
            "Property Facts from the Property Feed. Change these in the PMS; the Sync updates them here.",
          fields: factsFields,
        },
      ],
    },
  ],
}
