import {
  AccessibilityIcon,
  ArrowUpDownIcon,
  BabyIcon,
  BathIcon,
  CarIcon,
  CheckIcon,
  CircleDotIcon,
  CookingPotIcon,
  EyeIcon,
  FenceIcon,
  FlameIcon,
  FlameKindlingIcon,
  FootprintsIcon,
  Gamepad2Icon,
  MountainSnowIcon,
  PawPrintIcon,
  PlugZapIcon,
  SnowflakeIcon,
  TreePalmIcon,
  TvIcon,
  UmbrellaIcon,
  WashingMachineIcon,
  WavesIcon,
  WifiIcon,
  type LucideIcon,
} from "lucide-react"

/**
 * Amenity icon keys (the Site's, else the Feed's) to Lucide icons. Unknown
 * keys get a plain check, so a new Feed Amenity never breaks the filters.
 */
const icons: Record<string, LucideIcon> = {
  "hot-tub": BathIcon,
  spa: BathIcon,
  sauna: FlameIcon,
  pool: WavesIcon,
  "community-pool": WavesIcon,
  waves: WavesIcon,
  bbq: FlameKindlingIcon,
  "fire-pit": FlameKindlingIcon,
  fireplace: FlameIcon,
  flame: FlameIcon,
  deck: FenceIcon,
  "ocean-view": EyeIcon,
  "mountain-view": EyeIcon,
  "lake-view": EyeIcon,
  beachfront: TreePalmIcon,
  "beach-access": UmbrellaIcon,
  ski: MountainSnowIcon,
  "ski-in-ski-out": MountainSnowIcon,
  "walk-to-town": FootprintsIcon,
  wifi: WifiIcon,
  "air-conditioning": SnowflakeIcon,
  "game-room": Gamepad2Icon,
  "pool-table": CircleDotIcon,
  "home-theater": TvIcon,
  "full-kitchen": CookingPotIcon,
  "washer-dryer": WashingMachineIcon,
  elevator: ArrowUpDownIcon,
  "wheelchair-accessible": AccessibilityIcon,
  garage: CarIcon,
  "ev-charger": PlugZapIcon,
  "pet-friendly": PawPrintIcon,
  crib: BabyIcon,
}

export function amenityIcon(key: string | null): LucideIcon {
  return (key && icons[key]) || CheckIcon
}
